### PR TITLE
Rename app Start to Run

### PR DESCRIPTION
**Pull request by madhuravi**
Keep it consistent with RunForever

### CODE REVIEW

**Comment by madhuravi** [comment]
@uber-go/service-framework

**Comment by breerly** [comment]
As you probably already considered, it's not really an option to have `app.StartForever` to match `app.Start`. I think that it's OK that these don't match in naming, since they actually do different things:

* `App.Start` - Process startup
* `App.Stop` - Process shutdown
* `App.RunForever` - Process startup, block until SIGTERM/SIGITN, process shutdown

Totally open to naming changes, but lets make sure that start/stop map have naming symmetry and map conceptually to process startup and shutdown.

**Comment by madhuravi** [comment]
I like Start and Stop having symmetry as well. It's Start and RunForever that bothers me. They do the same thing, RunForever just calls Start and then waits for shutdown :)

If you have ideas on how to name them consistently, let me know.

**Comment by breerly** [comment]
Hmm... let me think about that today! I'll come back w/ a few ideas - maybe one of those will strike our interest :)

**Comment by anuptalwalkar** [comment]
I liked our previous naming `Start` `StartAsync` and `Stop` where `Start` is blocking start, and `StartAsync` gives back control to main.

**Comment by madhuravi** [comment]
I like Start and StartAsync as well :)

**Comment by breerly** [comment]
The `*Async` naming conventions strikes me as odd in Golang... let me dig around and see if there are any prevailing conventions - we aren't the first one to write libs w/ this type of functionality.

**Comment by breerly** [comment]
@madhuravi @anuptalwalkar lets jam in the meetin' tomorrow - I'll bring some notes/ideas

**Comment by madhuravi** [comment]
ping @breerly Can you share your ideas doc?

**Comment by breerly** [comment]
Hey @madhuravi, was OOO! Will follow up today!

**Comment by madhuravi** [comment]
sounds good, thanks!

**Comment by madhuravi** [comment]
reminder @breerly , want to get this closed out soon since it's one of the entry functions that is used everywhere.  Changes will be on multiple repos now :)

**Pull request closed without merging**
