### PR TITLE
Make yarpc module not specific to thrift

### PR DESCRIPTION
**Pull request by peter-edge**
The actual implemention of `yarpc.New` is not thrift-specific, this effectively just renames the associated code to remove the thrift reference.

### CODE REVIEW

**Comment by breerly** [comment]
Thank you @peter-edge - this change is a huge step in the right direction.

As usual, please get stamps from the UberFX team :)

**Comment by breerly** [comment]
@peter-edge what do you think about a test that uses a different encoding, like json?

If we had that, we would be confident that proto3 will drop in once we have support in YARPC.

**Comment by sectioneight** [comment]
Going to merge this as-is for now, if Peter or somebody on YARPC wants to add more tests for different encodings that'd be great, but trying to minimize conflicts and code churn here.

**Comment by peter-edge** [comment]
Ya sorry I didn't get to this, we'll add some more as we go.

**Pull request merged**
