### PR TITLE
Remove fx.Extract

### PR DESCRIPTION
**Pull request by breerly**
A "take it or leave it" followup PR for #577.

As far as we could tell, `fx.Extract` can be replaced with a single func passed to `fx.Invoke`, where the users treats that func as their original main. This lets them "extract" as many types as they need, use `fx.Run` instead of `fx.Start/Stop`, and gives the `fx.In` support by-way of `fx.Invoke`.

In other words, there would be no reason to close over a variable in `func main`, you could just treat the func passed to `fx.Invoke` as your main, and then use the variables from there.

This is an interesting one - if we can somehow survive this way, then that's a big win because fx.Extract adds an alternate "invoke-like" pathway that we have to explain and teach.

### Directions 

1. Read #577 first
2. Vote 👍 or 👎 on this PR
3. Discuss and comment on this PR instead of #577 

I will be scheduling a followup to go through all these so we can reject/accept.

### CODE REVIEW

**Comment by akshayjshah** [comment]
`Extract` can certainly be replaced by `Invoke`; under the hood, that's all it's doing.

I don't mind removing this, but it makes breaking glass notably more difficult - users who otherwise don't need to learn about `fx.In` and `fx.Out` now need to get all the way into the weeds.

I'd strongly prefer not to break this into a subpackage. Introducing tons of tiny packages isn't idiomatic - if `net/http` can be a single package, `fx` can too.

**Comment by breerly** [comment]
I was actually arguing that it made breaking glass more difficult... then I realized you don't actually need to close over variables in main if you write 1 invoke that acts like main instead.

**Comment by akshayjshah** [comment]
Of course they can - most services *can* be fully modeled as an `fx.App`. The purpose of `Extract` was to accommodate the vocal minority of internal gophers who don't *want* to use DI or fx's notion of lifecycle.

`Extract` provides an easy way to use fx only to manage the standard objects, letting the service owner manage lifecycle and most of main.

If there's debate about this, let's just delete it. It's purely additive and can be brought back later.

**Comment by breerly** [comment]
Again, just reporting the feedback. 

My take is that I think I'm ok with sacrificing some convenience to get an ultra-tight API up-front. This is 500 lines of code that makes something easier, but that something can be accomplished already with `fx.Invoke`.

**Comment by breerly** [comment]
From offline discussion:

> fx.Invoke can't actually be used in place of fx.Extract because the types an invoke func relies on are not always ready until lifecycle start. This makes using an invoke func in place of extract extra laborious because they would have to append an OnStart in order to ensure all types are ready. Extract on the other hand can pull types out of fx.App, and then app.Start can be called to ready eveything.

**Pull request closed without merging**
