### PR TITLE
Add service Host to YARPC registration

### PR DESCRIPTION
**Pull request by sectioneight**
This way we will have access to metrics/logging etc from the
registration function to plumb into custom dispatchers.

### CODE REVIEW

**Comment by sectioneight** [comment]
@uber-go/service-framework

**Comment by madhuravi** [comment]
Looks good. Tests?

**Comment by sectioneight** [comment]
The tests already cover this functionality...

**Comment by sectioneight** [comment]
Merging anyway, test failures are unrelated and being fixed by @anuptalwalkar

**Pull request merged**
