### PR TITLE
Trim timeout function

### PR DESCRIPTION
**Pull request by alsamylkin**
It is over engineered.

### CODE REVIEW

**Comment by alsamylkin** [comment]
Yep: https://github.com/uber-go/fx/blob/master/app_test.go#L175

**Comment by glibsm** [comment]
where is the breaking regression test that didn't work for the old solution?

**Comment by abhinav** [comment]
+1 on @glibsm's comment. Previous solution was broken. If fixing a bug, prefer to add a breaking test case first.

**Comment by alsamylkin** [comment]
It's not really broken, we were leaking a go routine. Sure, I'll add a test.

**Comment by alsamylkin** [comment]
Actually it is fine, we simply don't need a stop channel.

**Pull request merged**
