### PR TITLE
Update zap to rc3

### PR DESCRIPTION
**Pull request by peter-edge**

### CODE REVIEW

**Comment by glibsm** [comment]
Release notes from zap for reference

image

**Comment by glibsm** [comment]
pending CI, of course

**Comment by sectioneight** [comment]
Does this enable colorization by default in dev? if not, we should :)

**Comment by peter-edge** [comment]
It does not, you have to do:

```yaml
logging:
  encoding:
    levelEncoder: color
```

**Comment by peter-edge** [comment]
or `capitalColor`

**Comment by sectioneight** [comment]
Right. We should either update fx to do some dev magic or update the
scaffold.

**Comment by sectioneight** [comment]
Preferably the template. This doesn't seem like a good place for magic.

**Comment by peter-edge** [comment]
You know my feelings about code magic :)

**Comment by sectioneight** [comment]
✨

**Comment by anuptalwalkar** [comment]
+1 makes sense to be in scaffold.

**Comment by anuptalwalkar** [comment]
Something wrong with encoding. I tried both -  
```
logging:
  level: info
  encoding:
    levelEncoder: capitalColor
```
And
```
logging:
  level: info
  encoding:
    levelEncoder: color
```

2017/03/09 14:39:57 Failed to initialize moduleserrorfailed to build the logger: unknown encoding "map[levelEncoder:capitalColor]"

**Comment by peter-edge** [comment]
whoops s/encoding/encoderConfig/

**Pull request merged**
