### PR TITLE
Merge dev to master

### PR DESCRIPTION
**Pull request by alsamylkin**
Master is protected and I can't push the merge without review.

### CODE REVIEW

**Comment by anuptalwalkar** [comment]
lgtm!

**Comment by glibsm** [comment]
Are we doing a release or something? Tip of master should contain the
latest release.

**Comment by alsamylkin** [comment]
Master "is 21 commits behind dev". Not a release, just a long time no changes.

**Comment by glibsm** [comment]
This defeats part of the reason to have master. It means the tip no longer
points to a stable release, but rather an arbitrary point in the
development history.

**Comment by alsamylkin** [comment]
It is stable right now, but with the new module interface changes it will become unstable, so I simply want to fix that point first.

**Comment by alsamylkin** [comment]
No urge to do this now.

**Pull request closed without merging**
