### PR TITLE
Re-introduce a simple Sentry integration

### PR DESCRIPTION
**Pull request by akshayjshah**
This PR re-introduces a simple, `map[string]interface{}`-based Sentry integration. Performance should be comparable to the previous iteration of this code. This should close out the last remaining issue with the zap library upgrade.

@sectioneight, someone from your team should commandeer this PR and make sure documentation, etc. meet your standards.

### CODE REVIEW

**Comment by anuptalwalkar** [comment]
I was too early to cleanup docs here :)..  Generic question. What happened to integrating with filebeat?

**Comment by glibsm** [comment]
@anuptalwalkar prototyping this through filebeat is still going to happen. However, we don't want to take away Sentry integration entirely from beta customers for the time being

**Comment by akshayjshah** [comment]
@anuptalwalkar Yep, hopefully Filebeat integration is coming at some point. In the meantime, this preserves a working integration.

**Comment by akshayjshah** [comment]
Up to you. I suggest avoiding more config options unless users really need them, since it'll be very difficult to replicate them in Filebeat.

**Comment by anuptalwalkar** [comment]
Merging now for validation.

**Pull request merged**
