### PR TITLE
Remove parallel run for tracing filter

### PR DESCRIPTION
**Pull request by alsamylkin**
Test can fail/panic if someone is manipulating with a global tracer in parallel

### CODE REVIEW

**Comment by yutongp** [comment]
I am not sure if that is the cause of this issue. because i painced in another test:
```
2017/02/14 23:17:12 FAIL | ClientGet (0.01s)
2017/02/14 23:17:12      | panic: send on closed channel [recovered]
2017/02/14 23:17:12      |   panic: send on closed channel
2017/02/14 23:17:12      | goroutine 28 [running]:
2017/02/14 23:17:12      | panic(0x5affc0, 0xc4203b60a0)
2017/02/14 23:17:12      |   /usr/local/Cellar/go/1.7.4_1/libexec/src/runtime/panic.go:500 +0x1ae
2017/02/14 23:17:12      | testing.tRunner.func1(0xc42053a780)
2017/02/14 23:17:12      |   /usr/local/Cellar/go/1.7.4_1/libexec/src/testing/testing.go:579 +0x474
2017/02/14 23:17:12      | panic(0x5affc0, 0xc4203b60a0)
2017/02/14 23:17:12      |   /usr/local/Cellar/go/1.7.4_1/libexec/src/runtime/panic.go:458 +0x271
2017/02/14 23:17:12      | go.uber.org/fx/vendor/github.com/uber/jaeger-client-go.(*remoteReporter).Report(0xc4204d6300, 0xc4206580f0)
2017/02/14 23:17:12      |   go.uber.org/fx/vendor/github.com/uber/jaeger-client-go/reporter.go:220 +0x8b
2017/02/14 23:17:12      | go.uber.org/fx/vendor/github.com/uber/jaeger-client-go.(*tracer).reportSpan(0xc420572000, 0xc4206580f0)
2017/02/14 23:17:12      |   go.uber.org/fx/vendor/github.com/uber/jaeger-client-go/tracer.go:334 +0x15c
2017/02/14 23:17:12      | go.uber.org/fx/vendor/github.com/uber/jaeger-client-go.(*span).FinishWithOptions(0xc4206580f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
2017/02/14 23:17:12      |   go.uber.org/fx/vendor/github.com/uber/jaeger-client-go/span.go:215 +0x41e
2017/02/14 23:17:12      | go.uber.org/fx/vendor/github.com/uber/jaeger-client-go.(*span).Finish(0xc4206580f0)
2017/02/14 23:17:12      |   go.uber.org/fx/vendor/github.com/uber/jaeger-client-go/span.go:194 +0x64
2017/02/14 23:17:12      | go.uber.org/fx/modules/uhttp/client.tracingFilter.func1(0xc420658000, 0x8c8f80, 0xc4205a02d0, 0xc4200a8090, 0x0, 0x0)
2017/02/14 23:17:12      |   /var/folders/6r/3_p6gkbs5dsbq9p94js1c45m0000gn/T/go-build263668792/go.uber.org/fx/modules/uhttp/client/_test/_obj_test/client_filters.go:93 +0x658
2017/02/14 23:17:12      | go.uber.org/fx/modules/uhttp/client.FilterFunc.Apply(0x6ccfa8, 0xc420658000, 0x8c8f80, 0xc4205a02d0, 0xc4205a02d0, 0x8f08e0, 0x121f6)
2017/02/14 23:17:12      |   /var/folders/6r/3_p6gkbs5dsbq9p94js1c45m0000gn/T/go-build263668792/go.uber.org/fx/modules/uhttp/client/_test/_obj_test/client_filters.go:54 +0x6e
2017/02/14 23:17:12      | go.uber.org/fx/modules/uhttp/client.executionChain.Execute(0x1, 0xc420337500, 0x2, 0x2, 0x8c7c80, 0xc4200ec000, 0xc420658000, 0x142aa9, 0x1b00000020, 0x6cd4c0)
2017/02/14 23:17:12      |   /var/folders/6r/3_p6gkbs5dsbq9p94js1c45m0000gn/T/go-build263668792/go.uber.org/fx/modules/uhttp/client/_test/_obj_test/client.go:71 +0x17a
2017/02/14 23:17:12      | go.uber.org/fx/modules/uhttp/client.executionChain.RoundTrip(0x0, 0xc420337500, 0x2, 0x2, 0x8c7c80, 0xc4200ec000, 0xc420658000, 0xc4205a02a8, 0xc4205a02a0, 0xc4200788d8)
2017/02/14 23:17:12      |   /var/folders/6r/3_p6gkbs5dsbq9p94js1c45m0000gn/T/go-build263668792/go.uber.org/fx/modules/uhttp/client/_test/_obj_test/client.go:81 +0x74
2017/02/14 23:17:12      | go.uber.org/fx/modules/uhttp/client.(*executionChain).RoundTrip(0xc42031ced0, 0xc420658000, 0xc42031ced0, 0xed035f7f0, 0x31a3888c)
2017/02/14 23:17:12      |   <autogenerated>:5 +0x99
2017/02/14 23:17:12      | net/http.send(0xc420646000, 0x8c8fc0, 0xc42031ced0, 0xed035f7f0, 0x31a3888c, 0x8f0a60, 0xc420427000, 0xc420427000, 0x5a590)
2017/02/14 23:17:12      |   /usr/local/Cellar/go/1.7.4_1/libexec/src/net/http/client.go:256 +0x2ff
2017/02/14 23:17:12      | net/http.(*Client).send(0xc42031cea0, 0xc420646000, 0xed035f7f0, 0x31a3888c, 0x8f0a60, 0xc4205be020, 0x0, 0x1)
2017/02/14 23:17:12      |   /usr/local/Cellar/go/1.7.4_1/libexec/src/net/http/client.go:146 +0x1c8
2017/02/14 23:17:12      | net/http.(*Client).doFollowingRedirects(0xc42031cea0, 0xc420646000, 0x6cd4c8, 0x16, 0x0, 0x0)
2017/02/14 23:17:12      |   /usr/local/Cellar/go/1.7.4_1/libexec/src/net/http/client.go:528 +0x3cf
2017/02/14 23:17:12      | net/http.(*Client).Get(0xc42031cea0, 0xc420632040, 0x16, 0xc4315d5e89, 0x315d5e8900093a91, 0xed035f778)
2017/02/14 23:17:12      |   /usr/local/Cellar/go/1.7.4_1/libexec/src/net/http/client.go:418 +0xe3
2017/02/14 23:17:12      | go.uber.org/fx/modules/uhttp/client.TestClientGet(0xc42053a780)
2017/02/14 23:17:12      |   go.uber.org/fx/modules/uhttp/client/client_test.go:72 +0x92
2017/02/14 23:17:12      | testing.tRunner(0xc42053a780, 0x6ccf18)
2017/02/14 23:17:12      |   /usr/local/Cellar/go/1.7.4_1/libexec/src/testing/testing.go:610 +0xca
2017/02/14 23:17:12      | created by testing.(*T).Run
2017/02/14 23:17:12      |   /usr/local/Cellar/go/1.7.4_1/libexec/src/testing/testing.go:646 +0x530
2017/02/14 23:17:12 FAIL | go.uber.org/fx/modules/uhttp/client  0.224s
2017/02/14 23:17:12 ERROR:exit status 1
```

**Comment by yutongp** [comment]
I think we should dig into it a little bit more. And have some solutions when tests overwrite global variables like something I did here: https://github.com/uber-go/fx/pull/265

all tests touch global should teardown and cannot run parallel with each other.

**Comment by alsamylkin** [comment]
Ok, let me investigate a little more

**Comment by alsamylkin** [comment]
Made all uhttp client/filter tests to be sequential and added comment about parallel use of the client.

**Comment by yutongp** [comment]
should we remove parallel flag in client_test.go as well? some of them are using traceFilter

**Comment by alsamylkin** [comment]
Yeah, somehow, I've missed, that _testClient has tracing filter too.

**Pull request merged**
