### PR TITLE
Add nop config provider

### PR DESCRIPTION
**Pull request by alsamylkin**
We have Nop implementations for most interfaces, but not yet for a config provider.

### CODE REVIEW

**Comment by alsamylkin** [comment]
If users want to test a specific functionality, e.g. RegisterCallback always returns an error, the easiest way to do that will be embedding a NopConfigProvier, and they can't do this with a staticProvider, because it is private.

Another part is type preservation: we serialize objects to yaml and loose type information, uints, int8s will be converted to ints, float32s to float64.

**Comment by anuptalwalkar** [comment]
I see. You can simply define a variable to provider or provider group. something like this -

`var NopProvider = NewYAMLProviderFromBytes([]byte(""))`

then access it like -
`	NopProvider.RegisterChangeCallback("", nil)`

**Comment by alsamylkin** [comment]
How would it help in the above cases? This register change callback always returns nil, types still are going to be simplified..

**Comment by alsamylkin** [comment]
Yes, it is supposed to help writing tests by embedding in structs, and e.g. I am going to use this provider to test numerical conversions.

**Pull request merged**
